#!/bin/bash

echo "Running"

script_dir=$(dirname $0)
root_dir=$(realpath $script_dir/../..)

function control() {
  SHARDS_LOG_FILE=control.log $shards new $script_dir/server/control.shs ${@}
}

set -ex
# control action:run data:"$script_dir/gfx-cube.shs"
# control action:run data:"$script_dir/gfx-texture.shs"
# control action:run data:"$script_dir/gfx-gltf.shs"
# control action:run data:"$script_dir/gfx-gltf-anim.shs"
# control action:run data:"$script_dir/gfx-shader-translator-0.shs"
# control action:run data:"$script_dir/gfx-shader-translator-1.shs"
# control action:run data:"$script_dir/gfx-shader-translator-2.shs"
# control action:run data:"$script_dir/gfx-shader-translator-3.shs"
# control action:run data:"$script_dir/gfx-shader-translator-4.shs"
# control action:run data:"$script_dir/gfx-queue.shs"
# control action:run data:"$script_dir/gfx-read-texture.shs"
control action:run data:"$script_dir/gfx-pbr.shs"
# control action:run data:"$script_dir/ui-1.shs"
# control action:run data:"$script_dir/web-sandbox.shs"