#!/bin/bash

SHARDS_ROOT=$( cd "$(dirname "$0")" ; pwd -P )
echo "Using SHARDS_ROOT=${SHARDS_ROOT}"

pushd $SHARDS_ROOT/deps
echo "Setting up dependencies"
./bootstrap; Res=$?
if [ ! $Res -eq 0 ]; then
  echo "Failed to set-up dependencies ($Res)"
  exit 1
fi
popd

echo "Setting up tools"
pushd $SHARDS_ROOT/src/tools
./bootstrap; Res=$?
if [ ! $Res -eq 0 ]; then
  echo "Failed to set-up tools ($Res)"
  exit 1
fi
popd
