[package]
name = "shards-egui"
description = ""
license = "BSD-3-Clause"
version = "0.1.0"
authors = ["Giovanni Petrantoni <sinkingsugar@gmail.com>"]
edition = "2021"

[lib]
crate-type = ["rlib", "staticlib"]

[dependencies]
lazy_static = "1.5.0"
egui = { version = "0.34", features = ["persistence"] }
egui_commonmark = { version = "0.23", features = ["better_syntax_highlighting"] }
egui_dock = { version = "0.19", features = ["serde"] }
egui_extras = { version = "0.34", features = ["serde"] }
egui_memory_editor = { path = "../../../egui_memory_editor" }
egui_plot = { version = "0.35" }
syntect = { version = "5.2.0", default-features = false, features = [
    "default-fancy",
] }
enum-map = { version = "2.5.0" }
shards = { path = "../rust" }
shards-lang = { path = "../lang" }
pest = "2.7.1"
bitcode = { version = "0.6.3", features = ["serde"] }
compile-time-crc32 = "0.1.2"
nanoid = "0.4.0"
num-traits = "0.2"
serde = { version = "1", features = ["derive"] }

[build-dependencies]
bindgen = "0.72"
gfx-build = { path = "../gfx/rust/build" }
