[package]
name = "shards-geo"
description = "Geospatial operations for drone mission planning"
license = "BSD-3-Clause"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["rlib", "staticlib"]

[dependencies]
lazy_static = "1.5"
shards = { path = "../../rust" }
compile-time-crc32 = "0.1"
geo = "0.32"
geo-buffer = "0.2"
zip = "6.0"
