[package]
name = "shards-py"
description = "RustPython-based Python integration for Shards"
license = "BSD-3-Clause"
version = "0.1.0"
authors = ["Giovanni Petrantoni <sinkingsugar@gmail.com>"]
edition = "2021"

[lib]
crate-type = ["rlib", "staticlib"]

[dependencies]
lazy_static = "1.5.0"
shards = { path = "../../rust" }
compile-time-crc32 = "0.1.2"
# Disable default features to exclude ctypes and lzma
[dependencies.rustpython-vm]
git = "https://github.com/fragcolor-xyz/RustPython.git"
branch = "shards"
version = "0.4.0"
default-features = false
features = ["freeze-stdlib", "compiler", "stdio", "threading"]

[dependencies.rustpython-pylib]
git = "https://github.com/fragcolor-xyz/RustPython.git"
branch = "shards"
version = "0.4.0"
default-features = false
features = ["freeze-stdlib"]

[dependencies.rustpython-stdlib]
git = "https://github.com/fragcolor-xyz/RustPython.git"
branch = "shards"
version = "0.4.0"
default-features = false
features = ["compiler", "threading"]