[package]
name = "naga-native"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
naga = { path = "../wgpu/naga", features = ["wgsl-out", "serialize", "deserialize" ] }
bitflags = { version = "2.3.3" }

[patch.crates-io]
naga = { path = "../wgpu/naga" }
profiling = { path = "../profiling" } # Custom profiling fork for Tracy integration

[build-dependencies]
cbindgen = "0.24.0"
