name: Build (macOS)

on:
  workflow_dispatch:
    inputs:
      build-type:
        description: build in release or debug
        required: true
        default: Debug
        type: choice
        options:
          - Debug
          - Release
      run-tests:
        description: Run the tests?
        required: false
        default: false
        type: boolean
      run-subproject-tests:
        description: Run the subproject tests?
        required: false
        default: false
        type: boolean
  workflow_call:
    inputs:
      build-type:
        required: true
        default: Debug
        type: string
      run-tests:
        required: false
        default: false
        type: boolean
      run-subproject-tests:
        required: false
        default: false
        type: boolean

jobs:
  #
  # Build shards for macOS
  #
  macOS:
    name: Build (${{ github.event.inputs.build-type || inputs.build-type }})
    runs-on: macos-latest
    outputs:
      run-tests: ${{ steps.setup.outputs.run-tests }}
      run-subproject-tests: ${{ steps.setup.outputs.run-subproject-tests }}
      artifact-name: shards-macos-${{ steps.setup.outputs.build-type }}
      build-type: ${{ steps.setup.outputs.build-type }}
    steps:
      - name: Setup
        id: setup
        shell: bash
        run: |
          echo "build-type=${{ github.event.inputs.build-type || inputs.build-type }}" >> $GITHUB_OUTPUT
          echo "run-tests=${{ github.event.inputs.run-tests || inputs.run-tests }}" >> $GITHUB_OUTPUT
          echo "run-subproject-tests=${{ github.event.inputs.run-subproject-tests || inputs.run-subproject-tests }}" >> $GITHUB_OUTPUT
      - name: Checkout shards
        uses: actions/checkout@v3
        with:
          repository: fragcolor-xyz/shards
          fetch-depth: 1
          submodules: recursive
      - name: Set up dependencies
        run: |
          # sudo xcode-select --switch /Applications/Xcode_15.4.app
          brew install ninja clang-format
          RUSTUP_TOOLCHAIN=`cat rust.version`
          echo "RUSTUP_TOOLCHAIN=$RUSTUP_TOOLCHAIN" >> $GITHUB_ENV
          rustup toolchain install $RUSTUP_TOOLCHAIN
      - name: Build
        run: |
          cmake -Bbuild -G Ninja -DSPDLOG_ACTIVE_LEVEL="SPDLOG_LEVEL_DEBUG" -DSHARDS_DEFAULT_LOG_LEVEL="SPDLOG_LEVEL_DEBUG" -DSKIP_HEAVY_INLINE=1 -DWITH_SQLITE_VEC=ON -DCMAKE_BUILD_TYPE=${{ steps.setup.outputs.build-type }}
          cmake --build build --target shards
          cmake --build build --target test-runtime
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: shards-macos-${{ steps.setup.outputs.build-type }}
          path: |
            build/shards
            build/test-runtime
          if-no-files-found: error
          retention-days: 7

  #
  # Test shards on macOS
  #
  macOS-test:
    if: ${{ needs.macOS.outputs.run-tests == 'true' }}
    needs: macOS
    name: Test
    runs-on: macos-latest
    steps:
      - name: Setup
        id: setup
        run: |
          echo "build-type=${{ github.event.inputs.build-type || inputs.build-type }}" >> $GITHUB_OUTPUT
      - name: Checkout shards
        uses: actions/checkout@v3
        with:
          repository: fragcolor-xyz/shards
          fetch-depth: 1
          submodules: true
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ needs.macOS.outputs.artifact-name }}
          path: build
      - name: Test
        env:
          RUST_BACKTRACE: full
        run: |
          cd build
          chmod +x shards
          chmod +x test-runtime

          # Run test-runtime
          ./test-runtime
          # Run other tests
          ./shards new ../shards/tests/general.shs
          ./shards new ../shards/tests/zip-map.shs
          ./shards new ../shards/tests/strings.shs
          ./shards new ../shards/tests/table-compose.shs
          ./shards new ../shards/tests/variables.shs
          ./shards new ../shards/tests/subwires.shs
          ./shards new ../shards/tests/linalg.shs
          ./shards new ../shards/tests/math.shs
          ./shards new ../shards/tests/math_audio.shs
          ./shards new ../shards/tests/network.shs
          ./shards new ../shards/tests/network-ws.shs
          ./shards new ../shards/tests/struct.shs
          ./shards new ../shards/tests/fs-security.shs
          ./shards new ../shards/tests/fileops.shs
          ./shards new ../shards/tests/flows.shs
          ./shards new ../shards/tests/channels.shs
          ./shards new ../shards/tests/imaging.shs
          ./shards new ../shards/tests/http.shs
          ./shards new ../shards/tests/bigint.shs
          ./shards new ../shards/tests/brotli.shs
          ./shards new ../shards/tests/snappy.shs
          ./shards new ../shards/tests/expect.shs
          ./shards new ../shards/tests/rust.shs
          ./shards new ../shards/tests/crypto.shs
          ./shards new ../shards/tests/wire-macro.shs
          ./shards new ../shards/tests/branch.shs
          ./shards new ../shards/tests/audio.shs test-device:false
          ./shards new ../shards/tests/audio2.shs test-device:false
          ./shards new ../shards/tests/events.shs
          ./shards new ../shards/tests/complex-deserialize.shs
          ./shards new ../shards/tests/db.shs with-sqlite-vec:true
          ./shards new ../shards/tests/db-paths.shs
          ./shards new ../shards/tests/suspend-resume.shs
          ./shards new ../shards/tests/help.shs
          ./shards new ../shards/tests/whendone.shs
          ./shards new ../shards/tests/return.shs
          ./shards new ../shards/tests/table-seq-push.shs
          ./shards new ../shards/tests/failures.shs
          ./shards new ../shards/tests/traits.shs
          ./shards new ../shards/tests/llm.shs
          ./shards new ../shards/tests/stdio.shs <<< "Hello world"
          ./shards new ../shards/tests/jinja.shs
          ./shards new ../shards/tests/crdts.shs
          ./shards new ../shards/tests/crdt-benchmarks.shs
          ./shards new ../shards/tests/geo.shs
      - name: Test doc samples (non-UI)
        env:
          RUST_BACKTRACE: full
        run: |
          cd docs/samples
          for i in $(find shards -name '*.shs' \( ! -path '*UI*' ! -path '*GFX*' ! -path '*Dialog*' \));
          do
            echo "Running sample $i";
            ../../build/shards new run-sample.shs file:"$i" looped:false;
          done
  macOS-dll-shard:
    if: ${{ needs.macOS.outputs.run-subproject-tests == 'true' }}
    needs: macOS
    name: Subproject tests
    runs-on: macos-latest
    steps:
      - name: Download shards artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ needs.macOS.outputs.artifact-name }}
          path: shards-bin
      - name: Make shards executable
        run: |
          chmod +x shards-bin/shards
          chmod +x shards-bin/test-runtime
      - name: Checkout shards for headers
        uses: actions/checkout@v4
        with:
          repository: fragcolor-xyz/shards
          path: shards-source
          fetch-depth: 1
          submodules: recursive
      - name: Checkout external-base
        uses: actions/checkout@v4
        with:
          repository: sinkingsugar/shards-external-base
          path: shards-external-base
          fetch-depth: 1
          submodules: recursive
      - name: Set up dependencies
        run: |
          brew install ninja
      - name: Build DLL
        run: |
          cd shards-external-base
          cmake -GNinja -Bbuild -DSHARDS_DIR=$GITHUB_WORKSPACE/shards-source
          cmake --build build
      - name: Setup test environment
        run: |
          mkdir -p externals
          BUILD=$GITHUB_WORKSPACE/shards-external-base/build
          ls -la $BUILD
          cp $BUILD/*.dll externals/ || true
          cp $BUILD/*.dylib externals/ || true
          cp $BUILD/*.so externals/ || true
          ls -la externals
          cp -r externals $GITHUB_WORKSPACE/shards-external-base/
      - name: Run test
        env:
          RUST_BACKTRACE: full
          LOG_SHARDS: debug
        run: |
          cd shards-external-base
          ls -la 
          ls -la ./externals
          $GITHUB_WORKSPACE/shards-bin/shards ./test.shs
      - name: Create artifact
        uses: actions/upload-artifact@v4
        with:
          name: shards-external-base-${{ needs.macOS.outputs.build-type }}
          path: externals
          retention-days: 7
          if-no-files-found: error

  macOS-prometheus-shard:
    if: ${{ needs.macOS.outputs.run-subproject-tests == 'true' }}
    needs: macOS
    name: Build Prometheus Library
    runs-on: macos-latest
    steps:
      - name: Download shards artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ needs.macOS.outputs.artifact-name }}
          path: shards-bin
      - name: Make shards executable
        run: |
          chmod +x shards-bin/shards
          chmod +x shards-bin/test-runtime
      - name: Checkout shards for headers
        uses: actions/checkout@v4
        with:
          repository: fragcolor-xyz/shards
          path: shards-source
          fetch-depth: 1
          submodules: recursive
      - name: Checkout shards-prometheus
        uses: actions/checkout@v4
        with:
          repository: fragcolor-xyz/shards-prometheus
          path: shards-prometheus
          fetch-depth: 1
          submodules: recursive
      - name: Set up dependencies
        run: |
          brew install ninja zlib
      - name: Build prometheus library
        run: |
          cd shards-prometheus
          cmake -GNinja -Bbuild -DCMAKE_BUILD_TYPE=RelDebInfo -DSHARDS_DIR=$GITHUB_WORKSPACE/shards-source
          cmake --build build
      - name: Test prometheus library
        env:
          RUST_BACKTRACE: full
          LOG_SHARDS: debug
        run: |
          mkdir -p externals
          BUILD=$GITHUB_WORKSPACE/shards-prometheus/build
          ls -la $BUILD
          cp $BUILD/*.dll externals/ || true
          cp $BUILD/*.dylib externals/ || true
          cp $BUILD/*.so externals/ || true
          ls -la externals
      - name: Create artifact
        uses: actions/upload-artifact@v4
        with:
          name: shards-prometheus-${{ needs.macOS.outputs.build-type }}
          path: externals/
          retention-days: 7
          if-no-files-found: error

  macOS-shards-bg3:
    if: ${{ needs.macOS.outputs.run-subproject-tests == 'true' }}
    needs: macOS
    name: Build BG3 Shards
    runs-on: macos-latest
    steps:
      - name: Download shards artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ needs.macOS.outputs.artifact-name }}
          path: shards-bin
      - name: Make shards executable
        run: |
          chmod +x shards-bin/shards
          chmod +x shards-bin/test-runtime
      - name: Checkout shards for Rust modules
        uses: actions/checkout@v4
        with:
          repository: fragcolor-xyz/shards
          path: shards
          fetch-depth: 1
          submodules: recursive
      - name: Checkout shards-bg3
        uses: actions/checkout@v4
        with:
          repository: sinkingsugar/shards-bg3
          path: shards-bg3
          fetch-depth: 1
      - name: Set up dependencies
        run: |
          brew install ninja
          RUSTUP_TOOLCHAIN=`cat shards/rust.version`
          rustup toolchain install $RUSTUP_TOOLCHAIN
          rustup default $RUSTUP_TOOLCHAIN
      - name: Build shards-bg3
        run: |
          cd shards-bg3
          # Need to create the externals directory first, since we build to that using custom build.rs parameters
          mkdir -p test/externals
          SHARDS_PATH=$GITHUB_WORKSPACE/shards cargo build
      - name: Create artifact
        uses: actions/upload-artifact@v4
        with:
          name: shards-bg3-${{ needs.macOS.outputs.build-type }}
          path: shards-bg3/test/externals/bg3.dylib
          retention-days: 7
          if-no-files-found: error
  macOS-shards-rust:
    if: ${{ needs.macOS.outputs.run-subproject-tests == 'true' }}
    needs: macOS
    name: Build Rust Shards
    runs-on: macos-latest
    steps:
      - name: Download shards artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ needs.macOS.outputs.artifact-name }}
          path: shards-bin
      - name: Make shards executable
        run: |
          chmod +x shards-bin/shards
          chmod +x shards-bin/test-runtime
      - name: Checkout shards for Rust modules
        uses: actions/checkout@v4
        with:
          repository: fragcolor-xyz/shards
          path: shards
          fetch-depth: 1
          submodules: recursive
      - name: Checkout shards-rust-example
        uses: actions/checkout@v4
        with:
          repository: fragcolor-xyz/shards-rust-example
          path: shards-rust-example
          fetch-depth: 1
      - name: Set up dependencies
        run: |
          brew install ninja
          RUSTUP_TOOLCHAIN=`cat shards/rust.version`
          rustup toolchain install $RUSTUP_TOOLCHAIN
          rustup default $RUSTUP_TOOLCHAIN
      - name: Build shards-rust-example
        run: |
          cd shards-rust-example
          # Need to create the externals directory first, since we build to that using custom build.rs parameters
          mkdir -p test/externals
          SHARDS_PATH=$GITHUB_WORKSPACE/shards cargo build

      - name: Test shards-rust-example
        run: |
          cd shards-rust-example
          $GITHUB_WORKSPACE/shards-bin/shards test/test_calculator.shs
      - name: Create artifact
        uses: actions/upload-artifact@v4
        with:
          name: shards-rust-example-${{ needs.macOS.outputs.build-type }}
          path: shards-rust-example/test/externals/calculator.dylib
          retention-days: 7
          if-no-files-found: error
