name: Build (Wasm)

on:
  workflow_dispatch:
  workflow_call:

jobs:
  wasm32-emscripten:
    name: Build
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout shards
        uses: actions/checkout@v4
        with:
          repository: fragcolor-xyz/shards
          fetch-depth: 1
          submodules: recursive

      - name: Checkout emsdk
        uses: actions/checkout@v4
        with:
          repository: emscripten-core/emsdk
          path: emsdk
          fetch-depth: 1

      - name: Checkout emscripten fork
        uses: actions/checkout@v4
        with:
          repository: guusw/emscripten
          path: emscripten
          fetch-depth: 1
          ref: shards-4.0.1

      - name: Set up dependencies
        run: |
          sudo apt -y update
          sudo apt -y install build-essential git cmake wget ninja-build clang
          
          ./bootstrap
          export RUSTUP_TOOLCHAIN=`cat rust.version`
          echo "RUSTUP_TOOLCHAIN=$RUSTUP_TOOLCHAIN" >> $GITHUB_ENV
          rustup toolchain install $RUSTUP_TOOLCHAIN
          rustup +$RUSTUP_TOOLCHAIN target add wasm32-unknown-emscripten

          # Setup host toolchain
          export HOST_CC=`which cc`
          export HOST_AR=`which ar`
          echo "HOST_CC=$HOST_CC" >> $GITHUB_ENV
          echo "HOST_AR=$HOST_AR" >> $GITHUB_ENV

          # Workaround for linker not being found
          export CARGO_TARGET_X86_64_UNKNOWN_LINUX_GNU_LINKER=`which cc`
          echo "CARGO_TARGET_X86_64_UNKNOWN_LINUX_GNU_LINKER=$CARGO_TARGET_X86_64_UNKNOWN_LINUX_GNU_LINKER" >> $GITHUB_ENV

          # Use the prebuilt SDK tools/binaries (MAKE SURE VERSION IS COMPATIBLE)
          pushd emsdk
          ./emsdk install 4.0.1
          ./emsdk activate 4.0.1
          source ./emsdk_env.sh
          cat ./.emscripten
          export EM_CONFIG=$PWD/.emscripten
          popd
          
          # !!!! Use and setup emscripten fork
          export EMSCRIPTEN_ROOT=$(pwd)/emscripten
          pushd $EMSCRIPTEN_ROOT
          ./bootstrap
          popd

          # Stock emscripten
          # export EMSCRIPTEN_ROOT=emsdk/upstream/emscripten

          echo "EM_CONFIG=$EM_CONFIG" >> $GITHUB_ENV
          echo "EMSCRIPTEN_ROOT=$EMSCRIPTEN_ROOT" >> $GITHUB_ENV

      - name: Set up rust
        run: |
          rustup +$RUSTUP_TOOLCHAIN component add rust-src

      - name: Build
        run: |
          cmake -Bbuild -GNinja -DCMAKE_BUILD_TYPE=Release -DSKIP_HEAVY_INLINE=1 -DUSE_LTO=0 -DRUST_USE_LTO=0 -DEMSCRIPTEN_PTHREADS=ON -DCMAKE_TOOLCHAIN_FILE=$EMSCRIPTEN_ROOT/cmake/Modules/Platform/Emscripten.cmake
          cmake --build build --target shards

          echo "SHARDS_BUILD=$(pwd)/build" >> $GITHUB_ENV

      - name: Package build artifacts
        run: |
          # Copy distribution symbols
          pushd $SHARDS_BUILD
          mkdir dist
          cp shards-mt.wasm dist/
          cp shards-mt.js dist/

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: shards-wasm
          path: |
            build/dist/
          if-no-files-found: error
          retention-days: 7
